jobs:
  print_version:
    docker:
    - image: buildpack-deps:bionic-curl
    steps:
    - heroku/install
    - run: heroku --version
orbs:
  heroku:
    commands:
      install:
        steps:
        - run:
            command: |-
              if [[ $(command -v heroku) == "" ]]; then
                curl https://cli-assets.heroku.com/install.sh | sh
              else
                echo "Heroku is already installed. No operation was performed."
              fi
            name: Install Heroku CLI, if necessary
    description: Provides basic functionality for deploying to Heroku
    version: 2
version: 2
workflows:
  dev:
    jobs:
    - print_version
  version: 2

