jobs:
  deploy:
    executor: heroku/default
    steps:
    - checkout
    - heroku/deploy
orbs:
  heroku:
    commands:
      deploy:
        steps:
        - run:
            command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
              master
            name: Deploy Master to Heroku
      install:
        steps:
        - run:
            command: |
              if [[ $(command -v heroku) == "" ]]; then
                curl https://cli-assets.heroku.com/install.sh | sh
              else
                echo "Heroku is already installed. No operation was performed."
              fi
            name: Install Heroku CLI, if necessary
    description: Provides basic functionality for deploying to Heroku
    executors:
      default:
        docker:
        - image: buildpack-deps:{{parameters.tag}}
        parameters:
          tag:
            default: bionic
            type: string
    version: 2
version: 2
workflows:
  ci:
    jobs:
    - deploy
  version: 2

