version: 2

jobs:
  print_version:
    docker:
      - image: ubuntu:bionic
    steps:
      - heroku/install
      - run: heroku --version

workflows:
  version: 2
  dev:
    jobs:
      - print_version